import time
from pynput.keyboard import Key
from pynput.keyboard import KeyCode
from pynput.mouse import Button

""" Class for managing quicktyping resources """
class QuickTyper():
    def __init__(self, controller):
        self.controller = controller
    
    #Quickyl
    def quick_type(self, message):
        self.controller.press(Key.enter)
        self.controller.release(Key.enter)
        time.sleep(0.0125) #very small delay needed because unturned sucks
        
        self.controller.release(Key.shift) #in case you are sprinting (yes, you need this even after stopping the listener)
        self.controller.type(message)
        
        time.sleep(0.0125)
        self.controller.press(Key.enter)
        self.controller.release(Key.enter)
    
        #filters in Handler class handle inputs generated by quicktyping so no worries there